# Unicode symbols for emojis can be found at https://getsymbols.com/
format = """
$directory $git_branch $git_state $git_commit
$character """

[directory]
truncation_length = 3
truncate_to_repo  = false
truncation_symbol = "../"
format = "[$path](bold cyan)[$read_only]($read_only_style)"

[cmake]
disabled = true

[character]
#https://getemoji.com/
success_symbol = "ğŸ’"
error_symbol = "ğŸ‘»"

